FROM python:3.10

WORKDIR /app

# Requirements
COPY requirements-cpu.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY . /app

# Setting the PYTHONPATH is mandatory
ENV PYTHONPATH=/app 
CMD ["python", "deploy.py"]
